name: shop-furniture
services:
  shop-db:
    image: mysql:8.4.0
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_LOGIN}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
